---
title: "DS 201 Semester Project"
format: 
  html:
    theme: pulse
    toc: true
bibliography: semester_project.bib
---

## Overview

The semester project will incorporate all the components of a data analysis covered in the course throughout the semester applied to a data set of your choosing pending approval by the instructor. Various components of the project will be due at different times but you will have the opportunity to revise some components prior to the submission of the final product. 

A complete project, counting for 50% of the overall course grade will consist of the following:

- A data sheet describing the essential information about your chosen data set.  

- An initial exploratory data analysis for your chosen data set.  

- An appropriate analysis of your chosen data set with the goal to address a specific research question.  

- A project report developed using Quarto. You may view the rendered version of an example report [here](https://symphonious-crostata-5b1f0b.netlify.app/report/).

- Slides for a presentation summarizing your project. You will not actually present the slides. A rendered version of examples slides may be viewed [here](https://symphonious-crostata-5b1f0b.netlify.app/presentation/).

- A GitHub repository containing all code (appropriately documented) written and used in your project. An example project repository may be viewed [here](https://github.com/jmgraham30/baseball_weather/tree/main).

Your project report and presentation should be written as if it is addressed to a stake holder with some subject matter knowledge in the domain of application but not necessarily with a quantitative or programming background. 

## Project Instructions and Components

Begin your semester project by choosing a topic and finding a source for some data that you can analyze. The only real restriction is that you need to have enough data that is appropriate for applying the methods we will learn in the class. 

### Project Component 1

By the end of the third week of class, you should submit to the instructor a paragraph that addresses the following questions:

1. What is the topic that you want to focus on for your semester project? 

2. Why is the topic of focus for your project appropriate for data analysis?

3. What is the source for the data you will use for your project? Make sure to include a reference or link to your data source. 

### Project Component 2

The second component of the semester project due by the end of the sixth week of classes is your raw data together with a draft of your datasheet. Follow the same procedure as in the [Data Package Assignment](https://ds201assignments.netlify.app/data_package_assignment/) to create your datasheet.  Your datasheet should be submitted together with all the relevant data files. 


### Project Component 3

The third component of the semester project is due by the end of week nine and should include the results of your exploratory data analysis (EDA) for your chosen data set. This should include all the code you used to conduct an EDA together with a document that describes what you did and what you learned from the EDA. 


### Project Component 4

The fourth component, due by the end of week twelve of your semester project should be the results of your full analysis of your data. This can be any type of model as long as it is appropriate for your data set and you can justify why you used the type of model you did. This should include all the code and data needed to reproduce your results. 

### Final Submission

The final submission, due at the end of the scheduled final exam period for your semester project should consist of:

- A project report developed using Quarto. You may view the rendered version of an example report [here](https://symphonious-crostata-5b1f0b.netlify.app/report/).

- Slides for a presentation summarizing your project. You will not actually present the slides. A rendered version of examples slides may be viewed [here](https://symphonious-crostata-5b1f0b.netlify.app/presentation/).

- A GitHub repository containing all code (appropriately documented) written and used in your project. An example project repository may be viewed [here](https://github.com/jmgraham30/baseball_weather/tree/main).

With your final submission, you may also include a revised datasheet. 



